config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'articles#index'
	resources :articles
	resources :users, only: [:index, :show]
	resources :ages, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user

	validates :body, :topic, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.order('created_at DESC').page(params[:page]).per(8)
	end

	def new
		@article = Article.new
	end

	def show
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
		if @article.save
		  redirect_to articles_path, notice: '記事を作成しました'
		else
			redirect_to new_article_path, notice: '記事を入力してください'
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		article = Article.find(params[:id])
		article.update(article_params)
		redirect_to articles_path, notice: '記事を編集しました'
	end

	def destroy
		Article.delete(params[:id])
		redirect_to articles_path, notice: '記事を削除しました'
	end

	private

	def article_params
		params.require(:article).permit(:body, :topic).merge(user_id: current_user.id)
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@articles = Article.where(user_id: current_user.id)
	end
end

app/views/articles/_flash.html.haml
-if flash[:notice]
  %p.flash
    = flash[:notice]

app/views/articles/_form.html.haml
.main
  .main__box
    = form_for @article do |f|
      .main__box__topic
        =f.text_field :topic, placeholder: '題名', class: 'main__box__topic__text-field'
      .main__box__article
        =f.text_area :body, placeholder: '内容', class: 'main__box__article__textarea'
      %ul.main__box__function
        %li.main__box__function__edit
          = link_to '戻る', articles_path
        %li.main__box__function__destroy
          =f.submit '作成'

app/views/articles/edit.html.haml
= render partial: 'articles/form'

app/views/articles/index.html.haml
.header
  .header__user
    .header__user__name
      = current_user.name
    .header__user__logo
      ブログ一覧
    %ul.header__user__function
      %li.header__user__function__sign-in
        = link_to 'Signin', destroy_user_session_path, method: :delete, class: 'header__user__function__sign-in__character'
      %li.header__user__function__sign-out
        = link_to 'Signout', destroy_user_session_path, method: :delete, class: 'header__user__function__sign-out__character'
      %li.header__user__function__new
        = link_to 'Mypage', users_path(current_user.id), class: 'header__user__function__sign-in__character'

.blogs
  - if @articles
    - @articles.each do |article|
      .blogs__box
        = link_to article.topic, article_path(article.id), class: 'blogs__box__topic'
        .blogs__box__username
          = article.user.name + "さんの投稿"
= paginate @articles

app/views/articles/new.html.haml
= render partial: 'articles/flash'
= render partial: 'articles/form'

app/views/articles/show.html.haml
.main
  .main__box
    .main__box__topic
      = @article.topic
    .main__box__article
      = @article.body
    %ul.main__box__function
      %li.main__box__function__show
        = link_to 'back', articles_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Myblog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/index.html.haml
= render partial: 'articles/flash'

.header
  .header__user
    .header__user__name
      = current_user.name
    .header__user__logo
      myblog
    %ul.header__user__function
      %li.header__user__function__sign-in
        = link_to '一覧', articles_path, class: 'header__user__function__sign-in__character'
      %li.header__user__function__sign-out
        = link_to 'Signout', destroy_user_session_path, method: :delete, class: 'header__user__function__sign-out__character'
      %li.header__user__function__new
        = link_to 'New', new_article_path, class: 'header__user__function__new__character'

.main
  - if @articles.present?
    - @articles.each do |a|
      .main__box
        .main__box__topic
          = a.topic
        .main__box__article
          = a.body
        %ul.main__box__function
          %li.main__box__function__edit
            = link_to 'edit', edit_article_path(a.id)
          %li.main__box__function__destroy
            = link_to 'destroy', "/articles/#{a.id}", method: :delete